nav:
    - cs:
          - tcs:
                - lec01
                - lec02
                - lec03
                - lec04
                - lec05
                - lec06
                - lec07
                - lec08
                - lec09
                - lec10
                - lec11
                - lec12
          - rl:
                - fundamentals
                - value-based
          - db:
                - relational-model
                - introduction-to-sql
          - quantum:
                - spin
                - linear-algebra
                - spin-and-qubits
                - entanglement
                - bells-inequality
                - classic-logic-gates-and-circuits
                - quantum-gates-and-circuits
          - ads:
                - avl-tree
                - amortized-analysis
                - splay-tree
                - red-black-tree
                - b-plus-tree
                - leftist-heap
                - skew-heap
                - binomial-queue
          - others:
                - mit-missing-semester
                - c-language-cheatsheet
                - manuals-standards
    - ctf:
          - game:
                - zjuctf2024
          - crypto:
                - basis
                - aes
                - rsa
                - diffie-hellman
                - ecc
    - sci:
          - phy:
                - chapter-27
                - chapter-28
                - chapter-29-30
          - prob:
                - distribution
                - chapter-1
                - chapter-2
                - chapter-3
          - ma:
                - cheatsheet
                - prove-that
                - completeness-of-real-numbers
          - la:
                - prove-that
                - what-is
    - misc:
          - test:
                - customToken
                - latex
                - markdown

icon:
    cs: code
    ctf: flag
    sci: atom
    misc: box-archive
